#ifndef _H_TDR_ERROR_CODE
#define _H_TDR_ERROR_CODE


typedef enum 
{
    E_TDR_NOERROR = 0,
    E_TDR_ERROR = -1,	
    E_TDR_OUT_OF_MEMORY = -2,
	E_TDR_NOT_FOUND = -3,
	E_TDR_SYNTAX = -4,
	E_TDR_MISMATCH = -5,
	E_TDR_ERRNO = -6,
	E_TDR_BAD_FILE = -7,
	E_TDR_EOF = -8,	
	E_TDR_INTEGER_OVERFLOW = -9,
	E_TDR_IGNORE = -10,
	E_TDR_PLEASE_READ_ENUM_NAME = -11,
	E_TDR_FILE_IS_ALREADY_ON_THE_STACK = -12,

	E_TDR_NO_MEMORY = -15,
	E_TDR_CAN_NOT_OPEN_FILE = -16,
	E_TDR_CLOSE = -17,
    E_TDR_TBUS_NOT_ENOUGH_SPACE = -18,
    E_TDR_TOO_MANY_SOCKET = -19,
    E_TDR_BAD_PACKAGE = -20,
	E_TDR_MYSQL_ERROR = 21,
}tdr_error_code_t;

#define TDR_ERROR_CODE_NUM 21


#endif
